config/routes.rb
Rails.application.routes.draw do
  resources :widgets, only: [:index, :show]

  root :to => "widgets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  prepend_before_action :set_cookie
  before_action :check_cookie

  private

  def set_cookie
    cookies[:native_cookie] = SecureRandom.uuid if params[:set_cookie]
  end

  def check_cookie
    @cookie_val = cookies[:native_cookie] || "Not found"
  end
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController

  prepend_before_action :set_cookie
  before_action :check_cookie

  def index
    @widgets = (1..10).to_a
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper

  def callout_class(cookie_val)
    cookie_val == "Not found" ? "alert" : "success"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookiebook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/foundation/6.5.3/css/foundation.min.css" %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>

    <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" %>
    <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/foundation/6.5.3/js/foundation.min.js" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>

    <div class="grid-container fluid">
      <div class="grid-x grid-margin-x">
        <div class="cell">
          <div class="callout <%= callout_class(@cookie_val) %>">
            <h5>Cookie value is: <%= @cookie_val %></h5>
          </div>
        </div>
        <div class="cell">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/widgets/index.html.erb
<div class="grid-x">
  <div class="cell">
    <h1>Index</h1>
  </div>
  <% @widgets.each do |w| %>
    <div class="cell">
      <%= link_to "Widget #{w}", widget_path(w) %>
    </div>
  <% end %>
</div>

app/views/widgets/show.html.erb
<h1>Show</h1>